skress/Controllers/VisitorsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using skress.Models;
using System.Data;
using System.Data.SqlClient;

namespace skress.Controllers
{
    public class VisitorsController : Controller
    {
        private readonly string _connectionString = "Server=LAPTOP-P6JDQUOH\\SQLEXPRESS;Database=Ski_resort;Trusted_Connection=True;";

        public async Task<IActionResult> Index()
        {
            List<VisitorInfo> visitorData = new List<VisitorInfo>();

            using (SqlConnection conn = new SqlConnection(_connectionString))
            {
                using (SqlCommand cmd = new SqlCommand("GetUniqueVisitors", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    conn.Open();
                    using (SqlDataReader reader = await cmd.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            visitorData.Add(new VisitorInfo
                            {
                                Id_visitor = reader.GetInt32(0),
                                VisitorName = reader.GetString(1),
                                VisitorSurname = reader.GetString(2),
                                VisitorBirthday = reader.GetDateTime(3),
                                PassType = reader.IsDBNull(4) ? null : reader.GetString(4),
                                NumberOfEntries = reader.IsDBNull(5) ? (int?)null : reader.GetInt32(5),
                                EquipmentType = reader.IsDBNull(6) ? null : reader.GetString(6),
                                TrackName = reader.IsDBNull(7) ? null : reader.GetString(7),
                                TrackDifficulty = reader.IsDBNull(8) ? (int?)null : reader.GetInt16(8),
                                InstructorName = reader.IsDBNull(9) ? null : reader.GetString(9),
                                InstructorSurname = reader.IsDBNull(10) ? null : reader.GetString(10),
                                InstructorSpecialization = reader.IsDBNull(11) ? null : reader.GetString(11)
                            });
                        }
                    }
                }
            }

            return View(visitorData);

        }
    }
}

skress/Controllers/VisitorsTablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using skress.Models;

namespace skress.Controllers
{
    [AuthenticatedUser]
    public class VisitorsTablesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VisitorsTablesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: VisitorsTables
        public async Task<IActionResult> Index(string searchString)
        {
            string role = HttpContext.Session.GetString("Role");
            if (role != "Manager" && (role != "Admin")) // Проверяем роль пользователя
            {
                TempData["ErrorMessage"] = "У вас нет доступа к этой функции";
                return RedirectToAction("Index", "Home");
            }
            //создается запрос LINQ для выбора посетителя
            var visitor = from m in _context.VisitorsTable
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                visitor = visitor.Where(s => s.Name!.Contains(searchString));
            }

            return View(await visitor.ToListAsync());
            return _context.VisitorsTable != null ? 
                          View(await _context.VisitorsTable.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.VisitorsTable'  is null.");
        }

        

        // GET: VisitorsTables/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VisitorsTable == null)
            {
                return NotFound();
            }

            var visitorsTable = await _context.VisitorsTable
                .FirstOrDefaultAsync(m => m.Id_visitor == id);
            if (visitorsTable == null)
            {
                return NotFound();
            }

            return View(visitorsTable);
        }

        // GET: VisitorsTables/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VisitorsTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_visitor,Name,Surname,BirthdayDate,Sex")] VisitorsTable visitorsTable)
        {
            if (ModelState.IsValid)
            {
                _context.Add(visitorsTable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(visitorsTable);
        }

        // GET: VisitorsTables/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VisitorsTable == null)
            {
                return NotFound();
            }

            var visitorsTable = await _context.VisitorsTable.FindAsync(id);
            if (visitorsTable == null)
            {
                return NotFound();
            }
            return View(visitorsTable);
        }

        // POST: VisitorsTables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_visitor,Name,Surname,BirthdayDate,Sex")] VisitorsTable visitorsTable)
        {
            if (id != visitorsTable.Id_visitor)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visitorsTable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisitorsTableExists(visitorsTable.Id_visitor))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(visitorsTable);
        }

        // GET: VisitorsTables/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VisitorsTable == null)
            {
                return NotFound();
            }

            var visitorsTable = await _context.VisitorsTable
                .FirstOrDefaultAsync(m => m.Id_visitor == id);
            if (visitorsTable == null)
            {
                return NotFound();
            }

            return View(visitorsTable);
        }

        // POST: VisitorsTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VisitorsTable == null)
            {
                return Problem("Entity set 'ApplicationDbContext.VisitorsTable'  is null.");
            }
            var visitorsTable = await _context.VisitorsTable.FindAsync(id);
            if (visitorsTable != null)
            {
                _context.VisitorsTable.Remove(visitorsTable);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VisitorsTableExists(int id)
        {
          return (_context.VisitorsTable?.Any(e => e.Id_visitor == id)).GetValueOrDefault();
        }
    }
}

skress/Views/VisitorsTables/Create.cshtml
@model skress.Models.VisitorsTable

@{
    ViewData["Title"] = "Create";
}

<h1>Добавить посетителя</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthdayDate" class="control-label"></label>
                <input asp-for="BirthdayDate" class="form-control" />
                <span asp-validation-for="BirthdayDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Sex" /> @Html.DisplayNameFor(model => model.Sex)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

skress/Views/VisitorsTables/Delete.cshtml
@model skress.Models.VisitorsTable

@{
    ViewData["Title"] = "Delete";
}



<h3>Вы уверены, что хотите удалить эту запись?</h3>
<div>
    <h4>VisitorsTable</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthdayDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthdayDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sex)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sex)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id_visitor" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Назад к списку</a>
    </form>
</div>

skress/Views/VisitorsTables/Details.cshtml
@model skress.Models.VisitorsTable

@{
    ViewData["Title"] = "Details";
}

<h1>Детали</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id_visitor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id_visitor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthdayDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthdayDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sex)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sex)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id_visitor">Edit</a> |
    <a asp-action="Index">Назад к списку</a>
</div>

skress/Views/VisitorsTables/Edit.cshtml
@model skress.Models.VisitorsTable

@{
    ViewData["Title"] = "Edit";
}

<h1>Редактирование</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id_visitor" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthdayDate" class="control-label"></label>
                <input asp-for="BirthdayDate" class="form-control" />
                <span asp-validation-for="BirthdayDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Sex" /> @Html.DisplayNameFor(model => model.Sex)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

skress/Views/VisitorsTables/Index.cshtml
@model IEnumerable<skress.Models.VisitorsTable>

@{
    ViewData["Title"] = "Index";
}

<h1>Посетители</h1>

<p>
    <a asp-action="Create">Создание записи</a>
</p>
<form asp-controller="VisitorsTables" asp-action="Index" method="get">
    <p>
        Имя: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<form asp-controller="Visitors" asp-action="Index" method="get">
    <p>
        <input type="submit" value="Сформировать общую инфоромацию" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthdayDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sex)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthdayDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sex)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id_visitor">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.Id_visitor">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.Id_visitor">Удаление</a>
            </td>
        </tr>
}
    </tbody>
</table>